### ISSUE TITLE
Reproducibility issue

### ISSUE THREAD

**Issue by danielm1405** [rvl-lab-utoronto/BFP#1]
Hi,
I am trying to reproduce your results. However, I get the following error:
```bash
danielmarczak@danielmarczak:~/research/BFP$ python ./utils/main.py --project bfp --model bfp --dataset seq-cifar10 --buffer_size 200 --alpha_bfp 0 --exp_suffix derpp_bfp0
Traceback (most recent call last):
  File "/home/danielmarczak/research/BFP/./utils/main.py", line 19, in <module>
    from models import get_all_models
  File "/home/danielmarczak/research/BFP/models/__init__.py", line 18, in <module>
    mod = importlib.import_module('models.' + model)
  File "/home/danielmarczak/miniconda3/envs/bfp/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/danielmarczak/research/BFP/models/er_gm.py", line 15, in <module>
    from contlearn.utils.loss import LGMLoss
ModuleNotFoundError: No module named 'contlearn'
```

I could not find package `contlearn` anywhere. Where can I find this package?

**Comment by georgegu1997** [comment]
Hi, 

Thanks for bringing up this issue! These are some external imports from another repo. Now they are fixed and the BFP code does not depend on it anymore. Please pull the latest version and try running the command again. 

Best Regards,
Qiao
